# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GoogleTagManagerBridge' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GoogleTagManagerBridge

  pod 'Firebase/Core'
  pod 'GoogleTagManager'

  target 'GoogleTagManagerBridgeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GoogleTagManagerBridgeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
